---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
options(warn = -1) ## shut rgdal up
```

# listmap

<!-- badges: start -->
<!-- badges: end -->

The goal of listmap is to get thelist imagery. 

## Installation

You can install ...


## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(listmap)
library(raster)
for (ilayer in 3:14) {
  plotRGB(listmap(layer = ilayer))
}
```


```{r thenut}
ex <- c(16173799 + c(0, 2000), -4978125 + c(-500, 1500))
r <- raster(extent(ex), nrows = 1024, ncols = 1024, crs = "EPSG:3857")
plotRGB(listmap(r, layer = 4))
plotRGB(listmap(r, layer = 6))
plotRGB(listmap(r, layer = 13))


print(listmap:::layers)
```


## Code of Conduct

Please note that the listmap project is released with a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html). By contributing to this project, you agree to abide by its terms.
